export const PLATFORM_LABELS: Record<string, string> = {
  'PC (Microsoft Windows)': 'PC',
  Mac: 'Mac',
  Linux: 'Linux',
  DOS: 'DOS',
  'Web browser': 'Browser',
  'Legacy Computer': 'Legacy PC',

  'PlayStation 5': 'PS5',
  'PlayStation 4': 'PS4',
  'PlayStation 3': 'PS3',
  'PlayStation 2': 'PS2',
  PlayStation: 'PS1',
  'PlayStation Portable': 'PSP',
  'PlayStation Vita': 'PS Vita',
  'PlayStation VR': 'PSVR',
  'PlayStation VR2': 'PSVR2',

  'Xbox Series X|S': 'Xbox Series',
  'Xbox One': 'Xbox One',
  'Xbox 360': 'Xbox 360',
  Xbox: 'Xbox',

  'Nintendo Switch 2': 'Switch 2',
  'Nintendo Switch': 'Switch',
  'Wii U': 'Wii U',
  Wii: 'Wii',
  'Nintendo GameCube': 'GameCube',
  'Nintendo 64': 'N64',
  'Super Nintendo Entertainment System': 'SNES',
  'Super Famicom': 'Super Famicom',
  'Nintendo Entertainment System': 'NES',
  'Family Computer': 'Famicom',
  'Family Computer Disk System': 'Famicom Disk',
  Satellaview: 'Satellaview',
  '64DD': '64DD',
  'Super NES CD-ROM System': 'SNES CD-ROM',
  'New Nintendo 3DS': 'New 3DS',
  'Nintendo 3DS': '3DS',
  'Nintendo DSi': 'DSi',
  'Nintendo DS': 'DS',
  'Game Boy Advance': 'GBA',
  'Game Boy Color': 'GBC',
  'Game Boy': 'Game Boy',

  'Sega Mega Drive/Genesis': 'Mega Drive',
  'Sega Saturn': 'Saturn',
  Dreamcast: 'Dreamcast',
  'Sega CD': 'Sega CD',
  'Sega 32X': 'Sega 32X',
  'Sega Master System/Mark III': 'Master System',
  'Sega Game Gear': 'Game Gear',
  'SG-1000': 'SG-1000',

  iOS: 'iOS',
  Android: 'Android',
  'Windows Phone': 'Windows Phone',
  'Windows Mobile': 'Windows Mobile',
  'BlackBerry OS': 'BlackBerry',
  'Palm OS': 'Palm OS',
  'N-Gage': 'N-Gage',
  'Legacy Mobile Device': 'Legacy Mobile',
  'Amazon Fire TV': 'Fire TV',

  SteamVR: 'SteamVR',
  'Meta Quest 3': 'Quest 3',
  'Meta Quest 2': 'Quest 2',
  'Oculus Quest': 'Quest 1',
  'Oculus Rift': 'Rift',
  'Oculus VR': 'Oculus VR',
  'Windows Mixed Reality': 'Windows MR',
  Daydream: 'Daydream',
  'Gear VR': 'Gear VR',
  visionOS: 'visionOS',

  'Google Stadia': 'Stadia',
  'OnLive Game System': 'OnLive',

  'Atari ST/STE': 'Atari ST',
  'Atari 8-bit': 'Atari 8-bit',
  'Atari 2600': 'Atari 2600',
  'Atari 5200': 'Atari 5200',
  'Atari 7800': 'Atari 7800',
  'Atari Lynx': 'Atari Lynx',
  'Atari Jaguar': 'Atari Jaguar',
  'Atari Jaguar CD': 'Jaguar CD',

  Amiga: 'Amiga',
  'Amiga CD32': 'Amiga CD32',
  'Commodore C64/128/MAX': 'C64',
  'Commodore VIC-20': 'VIC-20',
  'Commodore 16': 'C16',
  'Commodore Plus/4': 'Plus/4',
  'Commodore CDTV': 'CDTV',

  'TurboGrafx-16/PC Engine': 'PC Engine',
  'Turbografx-16/PC Engine CD': 'PC Engine CD',
  'PC Engine SuperGrafx': 'SuperGrafx',
  'PC-9800 Series': 'PC-98',
  'PC-8800 Series': 'PC-88',
  'NEC PC-6000 Series': 'PC-6000',

  'Neo Geo AES': 'Neo Geo AES',
  'Neo Geo CD': 'Neo Geo CD',
  'Neo Geo MVS': 'Neo Geo MVS',

  'FM Towns': 'FM Towns',
  'FM-7': 'FM-7',
  'Sharp X68000': 'X68000',
  'Sharp X1': 'Sharp X1',
  MSX: 'MSX',
  MSX2: 'MSX2',

  'ZX Spectrum': 'ZX Spectrum',
  'Amstrad CPC': 'Amstrad CPC',
  'BBC Microcomputer System': 'BBC Micro',
  'Acorn Archimedes': 'Archimedes',
  'Apple II': 'Apple II',
  'Apple IIGS': 'Apple IIGS',

  '3DO Interactive Multiplayer': '3DO',
  'Philips CD-i': 'CD-i',
  ColecoVision: 'ColecoVision',
  Intellivision: 'Intellivision',
  WonderSwan: 'WonderSwan',
  'WonderSwan Color': 'WonderSwan Color',

  Arcade: 'Arcade',
};
