package com.levelup.model.enums;

public enum GamePlatform {

    ANY(null),

    // ── Modern ───────────────────────────────────────────────────────────────
    PC_MICROSOFT_WINDOWS("PC (Microsoft Windows)"),
    MAC("Mac"),
    LINUX("Linux"),
    IOS("iOS"),
    ANDROID("Android"),
    AMAZON_FIRE_TV("Amazon Fire TV"),
    WEB_BROWSER("Web browser"),
    NINTENDO_SWITCH_2("Nintendo Switch 2"),
    NINTENDO_SWITCH("Nintendo Switch"),
    PLAYSTATION_5("PlayStation 5"),
    PLAYSTATION_4("PlayStation 4"),
    XBOX_SERIES_X_S("Xbox Series X|S"),
    XBOX_ONE("Xbox One"),
    GOOGLE_STADIA("Google Stadia"),

    // ── Virtual Reality ──────────────────────────────────────────────────────
    META_QUEST_3("Meta Quest 3"),
    META_QUEST_2("Meta Quest 2"),
    PLAYSTATION_VR2("PlayStation VR2"),
    PLAYSTATION_VR("PlayStation VR"),
    OCULUS_QUEST("Oculus Quest"),
    OCULUS_RIFT("Oculus Rift"),
    OCULUS_VR("Oculus VR"),
    STEAM_VR("SteamVR"),
    WINDOWS_MIXED_REALITY("Windows Mixed Reality"),
    DAYDREAM("Daydream"),
    GEAR_VR("Gear VR"),
    VISION_OS("visionOS"),

    // ── PlayStation ──────────────────────────────────────────────────────────
    PLAYSTATION_3("PlayStation 3"),
    PLAYSTATION_2("PlayStation 2"),
    PLAYSTATION("PlayStation"),
    PLAYSTATION_PORTABLE("PlayStation Portable"),
    PLAYSTATION_VITA("PlayStation Vita"),

    // ── Xbox ─────────────────────────────────────────────────────────────────
    XBOX_360("Xbox 360"),
    XBOX("Xbox"),

    // ── Nintendo ─────────────────────────────────────────────────────────────
    WII_U("Wii U"),
    WII("Wii"),
    NINTENDO_GAMECUBE("Nintendo GameCube"),
    NINTENDO_64("Nintendo 64"),
    SUPER_NINTENDO_ENTERTAINMENT_SYSTEM("Super Nintendo Entertainment System"),
    NINTENDO_ENTERTAINMENT_SYSTEM("Nintendo Entertainment System"),
    NEW_NINTENDO_3DS("New Nintendo 3DS"),
    NINTENDO_3DS("Nintendo 3DS"),
    NINTENDO_DSI("Nintendo DSi"),
    NINTENDO_DS("Nintendo DS"),
    GAME_BOY_ADVANCE("Game Boy Advance"),
    GAME_BOY_COLOR("Game Boy Color"),
    GAME_BOY("Game Boy"),
    SUPER_FAMICOM("Super Famicom"),
    FAMILY_COMPUTER_DISK_SYSTEM("Family Computer Disk System"),
    FAMILY_COMPUTER("Family Computer"),
    SATELLAVIEW("Satellaview"),
    SUPER_NES_CD_ROM_SYSTEM("Super NES CD-ROM System"),

    // ── Sega ─────────────────────────────────────────────────────────────────
    DREAMCAST("Dreamcast"),
    SEGA_SATURN("Sega Saturn"),
    SEGA_MEGA_DRIVE_GENESIS("Sega Mega Drive/Genesis"),
    SEGA_MASTER_SYSTEM_MARK_III("Sega Master System/Mark III"),
    SEGA_GAME_GEAR("Sega Game Gear"),
    SEGA_CD("Sega CD"),
    SEGA_32X("Sega 32X"),
    SG_1000("SG-1000"),

    // ── Arcade & PC Classics ─────────────────────────────────────────────────
    ARCADE("Arcade"),
    DOS("DOS"),
    AMIGA("Amiga"),
    AMIGA_CD32("Amiga CD32"),
    AMSTRAD_CPC("Amstrad CPC"),
    AMSTRAD_PCW("Amstrad PCW"),
    APPLE_II("Apple II"),
    APPLE_IIGS("Apple IIGS"),
    ACORN_ARCHIMEDES("Acorn Archimedes"),
    ACORN_ELECTRON("Acorn Electron"),
    ATARI_ST_STE("Atari ST/STE"),
    ATARI_8_BIT("Atari 8-bit"),
    BBC_MICROCOMPUTER_SYSTEM("BBC Microcomputer System"),
    COMMODORE_C64_128_MAX("Commodore C64/128/MAX"),
    COMMODORE_CDTV("Commodore CDTV"),
    COMMODORE_PLUS_4("Commodore Plus/4"),
    COMMODORE_VIC_20("Commodore VIC-20"),
    COMMODORE_16("Commodore 16"),
    FM_7("FM-7"),
    FM_TOWNS("FM Towns"),
    MSX("MSX"),
    MSX2("MSX2"),
    NEC_PC_6000_SERIES("NEC PC-6000 Series"),
    PC_8800_SERIES("PC-8800 Series"),
    PC_9800_SERIES("PC-9800 Series"),
    PC_ENGINE_SUPERGRAFX("PC Engine SuperGrafx"),
    SHARP_MZ_2200("Sharp MZ-2200"),
    SHARP_X1("Sharp X1"),
    SHARP_X68000("Sharp X68000"),
    TEXAS_INSTRUMENTS_TI_99("Texas Instruments TI-99"),
    TRS_80("TRS-80"),
    TRS_80_COLOR_COMPUTER("TRS-80 Color Computer"),
    ZX_SPECTRUM("ZX Spectrum"),

    // ── Legacy & Other ───────────────────────────────────────────────────────
    THREE_DO_INTERACTIVE_MULTIPLAYER("3DO Interactive Multiplayer"),
    SIXTY_FOUR_DD("64DD"),
    ATARI_2600("Atari 2600"),
    ATARI_5200("Atari 5200"),
    ATARI_7800("Atari 7800"),
    ATARI_JAGUAR("Atari Jaguar"),
    ATARI_JAGUAR_CD("Atari Jaguar CD"),
    ATARI_LYNX("Atari Lynx"),
    AY_3_8606("AY-3-8606"),
    BLACKBERRY_OS("BlackBerry OS"),
    BLU_RAY_PLAYER("Blu-ray Player"),
    CDC_CYBER_70("CDC Cyber 70"),
    COLECOVISION("ColecoVision"),
    DIGIBLAST("Digiblast"),
    DVD_PLAYER("DVD Player"),
    HANDHELD_ELECTRONIC_LCD("Handheld Electronic LCD"),
    HP_2100("HP 2100"),
    INTELLIVISION("Intellivision"),
    LASER_ACTIVE("LaserActive"),
    LEAPSTER_EXPLORER_LEADPAD_EXPLORER("Leapster Explorer/LeadPad Explorer"),
    LEGACY_COMPUTER("Legacy Computer"),
    LEGACY_MOBILE_DEVICE("Legacy Mobile Device"),
    N_GAGE("N-Gage"),
    NEO_GEO_AES("Neo Geo AES"),
    NEO_GEO_CD("Neo Geo CD"),
    NEO_GEO_MVS("Neo Geo MVS"),
    ONLIVE_GAME_SYSTEM("OnLive Game System"),
    OOPARTS("OOParts"),
    OUYA("Ouya"),
    PALM_OS("Palm OS"),
    PANASONIC_M2("Panasonic M2"),
    PDP_10("PDP-10"),
    PDP_11("PDP-11"),
    PHILIPS_CD_I("Philips CD-i"),
    PLUG_AND_PLAY("Plug & Play"),
    TAPWAVE_ZODIAC("Tapwave Zodiac"),
    TATUNG_EINSTEIN("Tatung Einstein"),
    TURBOGRAFX_16_PC_ENGINE("TurboGrafx-16/PC Engine"),
    TURBOGRAFX_16_PC_ENGINE_CD("Turbografx-16/PC Engine CD"),
    VECTREX("Vectrex"),
    WINDOWS_MOBILE("Windows Mobile"),
    WINDOWS_PHONE("Windows Phone"),
    WONDERSWAN("WonderSwan"),
    WONDERSWAN_COLOR("WonderSwan Color"),
    ZEEBO("Zeebo");

    private final String displayName;

    GamePlatform(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
